version: '2'
services:

  db:
    env_file: .env
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bundle exec rails server --port 3000 --binding 0.0.0.0"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/myapp
    volumes_from:
      - bundle

  bundle:
    image: startertemplate_web
    volumes:
      - /bundle
    command: echo "Loading up bundled gems!"
